### ISSUE TITLE
To GIL or not to GIL

### ISSUE THREAD

**Issue by McSinyx** [McSinyx/palace#10]
As [described in Cython's documentation](https://cython.readthedocs.io/en/latest/src/userguide/external_C_code.html#declaring-a-function-as-callable-without-the-gil), the Python GIL may need some special care.  Currently ~~all C++ classes are declared with `nogil`~~ *C++ routines are randomly marked with `nogil` and `with gil`*, and I am ~~un~~sure ~~whether~~ it is *not a* good practice.

Edit: the acquire and release of GIL are definitely problematic, and so far all discovered deadlocks are with resource loading:
1. Access to a buffer being `cache`d, either via `Buffer` or `free` (GH-73).
2. Streaming a decoder defined in Python (deriving from `BaseDecoder`).  Note that if it's loaded into a `Buffer`, the caching process is done on the main thread and thus no deadlock occurs.
3. Loading resources using custom `FileIO`, either as a stream (`decode`) or as a buffer.  This can either be a deadlock or a segfault.

**Comment by McSinyx** [comment]
A minimal example to reproduce would be
```python
from palace import *

use_fileio(lambda name: open(name, 'rb'))
with Device() as dev, Context(dev) as ctx, decode('audio file').play(12345, 6) as src:
    while src.playing: ctx.update()
```

**Comment by McSinyx** [comment]
I'd be grateful if you two @Huy-Ngo and @9a24f0 can do a little bit of research on this and try to solve it.  If none of us figure out a fix by the end of avril, we can declare this as a technical debt and precede to release v0.2 anyway.

Edit: it's the end of the month, this is dropped from the list of 0.2-blocking issues.

**Comment by McSinyx** [comment]
Since 1.0 is supposed to be the *stable* version, this should be fixed then.

**Comment by Huy-Ngo** [comment]
> C++ routines are randomly marked with `nogil` and `with gil`

I'm a bit confused here. Which routines are marked with `with gil`? As I can see, none in alure.pxd is marked with `with gil`. Do you mean the ones in Cython's implementation?

**Comment by McSinyx** [comment]
There are C++ functions defined in `palace.pyx` too (mostly for interfacing, e.g. Decoder, MessageHandler, FileIO).

**Comment by McSinyx** [comment]
*Migrated to [SourceHut TODO ~cnx/palace#1](https://todo.sr.ht/~cnx/palace/1).*
