### ISSUE TITLE
Distinguish data descriptors' permissions in their docstrings

### ISSUE THREAD

**Issue by McSinyx** [McSinyx/palace#102]
In continuation of 83315de9c8f87c7b8d4213607a1b177751058dc6 and  sphinx-contrib/napoleon#22: Currently we have three sorta data descriptors:
1. Read-only properties: decorated by `@getter`, which is an alias of CPython's `@property`.
2. Write-only properties: decorated by `@setter`, which is also an alias of CPython's `@property`
3. Read-write properties: decorated by `@property` and `@XXX.setter`, whose codes are *specially handled by **Cython***

Due to sphinx-doc/sphinx#7448, (3) isn't rendered with the prefix *property* by Sphinx.  Until this gets fix, (3) already stands out from the rest.  Nevertheless, my proposal is as follows
1. Use `Returns` to document *all* read-only properties
2. Use `Parameters` to document *all* write-only properties
3. Use `Attributes` to document multi-value read-write properties, or when their type needs special attention (at least until sphinx-doc/sphinx#7383 gets fix)

**Comment by 9a24f0** [comment]
@McSinyx have you forgotten that we have lecture today?

**Comment by McSinyx** [comment]
Probably, gentle ping on the issue though!

**Comment by McSinyx** [comment]
In the process could you please also fix [the docs on return value](https://mcsinyx.github.io/palace/html/reference/decoder.html#palace.Decoder.play) of `Decoder.play`?

**Comment by McSinyx** [comment]
Heads up: Sphinx is confused by the `Attributes` used for read-write properties:

    docstring of palace.Source.outer_cone_gains:3: WARNING: duplicate object description of palace.Source.gain, other instance in reference/source, use :noindex: for one of them

I suggest using either `Parameters` or `Returns` instead then, but I'm not sure which is better.

Edit: let's go with `Return`.

**Comment by McSinyx** [comment]
I've just scanned for `Tuple[` in palace.pyx and it seems that this can be closed now.
