### ISSUE TITLE
Is it Possible to Redirect audio Output to wav Numpy Array or File?

### ISSUE THREAD

**Issue by caliuf** [McSinyx/palace#113]
Hi everyone!
I was wondering if is it possible to not having the audio output played directly on jack, but just returned as a numpy array or outputted directly on a file.

This will be helpful for further processing, recording, etc.

As usual if this happens to be a feature request, I'm willing to work on it :-)

Many thanks in advance!

**Comment by McSinyx** [comment]
Hi, [MessageHandler.buffer_loading](https://mcsinyx.github.io/palace/html/reference/context.html#palace.MessageHandler.buffer_loading) will give you access to the raw (decoded) audio data, which you can use for some primitive processing (e.g. volume or pitch/speed).  IIRC it is not fast to convert a Python buffer (backed by a C++ array) to NumPy to operate on but there might be some magic tricks that allow one to use the memory directly as a NumPy array that I'm not aware of.

Though I'd be grateful if you can work it out, it might not worth the effort:
* For real-time processing it would be hell to synchronize the filter apply on the data and the playback—alure doesn't really provide a friendly interface for custom DSP filters.  Your best bet would be finding/writing such effect for OpenAL and port it to alure instead.  Chorus and reverb are a tiny subset of effects defined in openal-soft that has been ported to alure.
* For recording, please see [a discussion on Reddit I had a while ago](https://old.reddit.com/r/Python/comments/fx42wf/we_made_a_3d_audio_library_with_efx_and_codecs/fmscmrj/).  TL;DR for now please capture from the sound server you're using.

**Comment by caliuf** [comment]
After a quick code look, I realized it will probably take more time to me to get how the C++ porting stuff works (and your time too in answering my questions probably :-)), than what it's reasonable.

So I opted for jack plumbing. If it could be useful for someone else other than me I can add an example to the code (or a chapter to the tutorial if have time).

Just another curiosity: you said that any sound server can be used, but following the tutorial with just pulseaudio and no jack server lot of warnings and errors are printed and nothing is audible, so I guessed it was a sort of requirement. Is it expected to work out of the box or there's some trick to do?

Thanks again!

**Comment by McSinyx** [comment]
> following the tutorial with just pulseaudio and no jack server lot of warnings and errors are printed and nothing is audible, so I guessed it was a sort of requirement. Is it expected to work out of the box or there's some trick to do?

We expected it to work out of the box (@Huy-Ngo and @9a24f0: can you confirm this?), and the *no jack jack server* thing is part of OpenAL fallback while trying to find the audio backend.  Could you please try with setting the environment variable ALSOFT_LOGLEVEL to 3 to see if there's any additional info?

For explicitly setting audio backend, you can try method mentioned in https://github.com/kcat/openal-soft/issues/280#issuecomment-482763779.

**Comment by caliuf** [comment]
Interesting, I tried again now and it works out of the box as expected.

Messages printed from AL Lib are now just warnings, so I wonder if my strains to get jack working with my bluetooth earphones have somehow fixed something.

I'm sure that it wasn't working before, since I remember a couple of errors ("AL lib: (EE)") that are now fortunately gone. Sorry, I'm no longer able to reproduce the issue

**Comment by caliuf** [comment]
Let me now if it can be useful if I add a code example on how to output the final audio to a file, once I figured it out

**Comment by McSinyx** [comment]
Audio on GNU/Linux has always been confusing, no worries :smile:  Regarding

> if it can be useful if I add a code example on how to output the final audio to a file

Note that it would be highly platform/audio backend dependent.  I'm unsure of the exact use case, personally I'd go with any generic screen recorder and use ffmpeg to extract the audio.  You can try `sounddevice` if you want to use Python and have the audio directly.

**Comment by Huy-Ngo** [comment]
>> following the tutorial with just pulseaudio and no jack server lot of warnings and errors are printed and nothing is audible, so I guessed it was a sort of requirement. Is it expected to work out of the box or there's some trick to do?
>
> We expected it to work out of the box (@Huy-Ngo and @9a24f0: can you confirm this?)

Yes, I also have these warnings. I don't quite remember since when I've been seeing these, but it still works nonetheless so I didn't try to figure out why :stuck_out_tongue: 

```
AL lib: (WW) Cannot connect to server socket err = No such file or directory
AL lib: (WW) Cannot connect to server request channel
AL lib: (WW) jack server is not running or cannot be started
AL lib: (WW) JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
AL lib: (WW) JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
AL lib: (WW) jack_client_open() failed, 0x11
AL lib: (WW) Failed to initialize backend "jack"
AL lib: (EE) Failed to set real-time priority for thread
AL lib: (EE) Failed to set real-time priority for thread
```

**Comment by caliuf** [comment]
Ha ha, ok, I'm relieved :smile: 

Thanks for `sounddevice` suggestion, I'm going to try it

**Comment by McSinyx** [comment]
@caliuf, do you still want to add such functionality to palace?  Otherwise you can close the issue.

**Comment by caliuf** [comment]
@McSinyx Sorry for the late reply. I tried both sounddevice and jack client, I stuck with the latter for the flexibility.

Thanks!
