### ISSUE TITLE
Online documentation doesn't look so good on mobile

### ISSUE THREAD

**Issue by McSinyx** [McSinyx/palace#119]
The alabaster Sphinx theme doesn't fit narrow screen very well:

![20200930_21h02m58s_grim](https://user-images.githubusercontent.com/13689192/94695850-9f57b080-0360-11eb-8879-777ce35b46b2.png)

**Comment by MostDeadDeveloper** [comment]
Hi McSinyx ! Can I work on this? I wanna try and give it a go

**Comment by McSinyx** [comment]
Sure and thanks for checking us out!  BTW if you found this via Hacktoberfest, you might want to make sure the PR is filed in October :smile:

**Comment by MostDeadDeveloper** [comment]
Haha yea, I will be submitting the PR probably in a few days. 

I just went for a slight repo hunting since I was bored, but yea I was kinda interested in the project and it was a good first issue so which is why i am here. XD

I will give any updates on any important clarifications or progress.

**Comment by MostDeadDeveloper** [comment]
ahhh they revisioned hacktoberfest because of spam, LMAO.

Well I will still be working on it, sending a PR soon.

**Comment by McSinyx** [comment]
FYI I've just opted this repo in for Hacktoberfest, and that solving this is (code-wise) as simple as changing the theme as defined here: https://github.com/McSinyx/palace/blob/74a9989e53a98a61689251ff064664c4e67d1b3f/docs/source/conf.py#L30-L31

For the list of themes for Sphinx, please refer to [sphinx-themes](https://sphinx-themes.github.io/sphinx-themes.org).  The main work is to choose something visually pleasing across all elements we use in the docs (just skim through them) and not buggy (I was very tempted to use [furo](https://github.com/pradyunsg/furo) but it doesn't seem ready).

**Comment by McSinyx** [comment]
@MostDeadDeveloper, you don't have to open new PRs like that, just push new changes and we can rebase the commits later. (We have a bot wired to the matrix room and it's been quite noisy in the last few minutes :smile:)

**Comment by MostDeadDeveloper** [comment]
Added a PR #124 

I used the sphinx RTD Theme for it was mobile ready and had a similar design to Alabaster. Please check if it solves the issue and if it fits your tastes. 

Source : https://github.com/readthedocs/sphinx_rtd_theme

**Comment by MostDeadDeveloper** [comment]
> @MostDeadDeveloper, you don't have to open new PRs like that, just push new changes and we can rebase the commits later. (We have a bot wired to the matrix room and it's been quite noisy in the last few minutes smile)

Woops sorry, yeaaa my bad.
