### ISSUE TITLE
Future hosting and CI/CD plans

### ISSUE THREAD

**Issue by McSinyx** [McSinyx/palace#128]
Per the recent change in [policy on Travis CI](https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing), we've just enough *credits* to migrate to another platform.  In addition, I want to take this chance and move off GitHub, at least as the primary development platform as well, due to the abuses and harms it has done to the free software in general. <sup>I don't think palace or any of its core devs is subjected to the discrimination GitHub imposes, but let's run before that happens and not try not support such company.</sup>

Here are the list of services we are currently using:

1. Code hosting: GitHub
2. Issue tracker: GitHub issues
3. Patches review: GitHub PR
4. CI/CD
   - Travis CI (GNU/Linux and macOS build)
   - GitHub action (linting and docs)
   - AppVeyor (Windows build, but doesn't work)
5. Documentations: GitHub pages
6. Real-time communication: Matrix

I believe for resiliency, it's best to use as less proprietary software as possible:

- For 1, 2 and 3, we can use either [SourceHut](https://sourcehut.org), Gitea and GitLab (but **not** gitlab.com)
- For 4 we can use either SourceHut (only GNU/Linux), GitLab CI (GNU/Linux, macOS and Windows) or Zuul
- For 5 we can use GitLab pages (freedesktop.org seems to offer the service, but we'll need to ask for the domain), or use ReadTheDocs (in this case we'll need to modify the module to be importable w/o audio backend though)
- For 6, we don't need to do anything, Matrix is free software

Given that development has slowed down during the last few months (the API has been stable for half a year now) and Windows and macOS support is not foreseeable, I *think* it's worth moving to SourceHut:

1. Host code on git.sr.ht
2. Track bugs on todo.sr.ht
3. [Patches and discussion on lists.sr.ht](https://lists.sr.ht/~cnx/palace)
4. CI/CD on builds.sr.ht and possibly GitLab CI if we figure out how to build for macOS and Windows
5. Documentations on GitLab pages

The main reasons to choose SourceHut are

1. builds.sr.ht is amazing: being able to SSH into a build VM is heaven!
2. Mailing lists are more resilient than centralized PRs/MRs
3. Personally I find the lack of contribution count more healthy for my mentality

GitLab supports mirroring out-of-box so integrating it won't be a problem.  As for the host, I'm thinking about gitlab.freedesktop.org.

**Comment by Huy-Ngo** [comment]
Why *not* gitlab.com though?

**Comment by McSinyx** [comment]
[For public repos, GitLab.com *offer* the proprietary Gold plan](https://about.gitlab.com/handbook/marketing/strategic-marketing/tiers/#open-source-projects-on-gitlabcom-get-all-gold-features), which doesn't seem to be opt-out'able.  That being said, I have no opposition against using GitLab.com for secondary CI/CD (macOS and Windows) and docs.

**Comment by McSinyx** [comment]
Travis limited credits gave me too much anxiety, [I moved everything to SourceHut](https://sr.ht/~cnx/palace).  Documentation relating to hosting and CI/CD are yet to be updated, so feel free to send me patches!  [git send-email](https://git-send-email.io) is the way.

I'll wait a week before archiving this GitHub repository.

**Comment by McSinyx** [comment]
[0.2.4 has been released with everything working](https://lists.sr.ht/~cnx/palace/%3CC714GU0C2U5B.2LRGIKS3RBYUX%40debian%3E), so I'm closing this.  Discussion about moving from GitLab.com shall take place on the mailing list.
