### ISSUE TITLE
[aux-eff] Implementing `SourceSend` struct

### ISSUE THREAD

**Issue by Huy-Ngo** [McSinyx/palace#23]
The struct `SourceSend` is used in the class `AuxiliaryEffectSlot`.

I tried to implement the struct `SourceSend` by mimicking `AttributePair`. It failed to compile.

See [my latest commit](https://github.com/McSinyx/palace/commit/9474e1f97c470497bf1c751700dfa12824777b47) and [log](https://gist.github.com/Huy-Ngo/caa512063f4aa1966e1b8fb450ee236b).

Hopefully someone can point out where I got it wrong.

**Comment by McSinyx** [comment]
`mkssnds` (oh fuck what is this lol, `mkattr` (or any name decay) is bad, but everybody knows what `mk` and `attr` stands for; in this case use sth like `unpack_source_send`) got the signature (and purpose) inverse: from `alure.AuxiliaryEffectSlot.get_source_send()` you get a vector of `SourceSend`s, so to unpack this you need to loop over the `SourceSend`s and `yield` tuples of (source, send) (assuming gererator works in Cython `cdef`--lazy evaluation is preferred over, ehm, the nonlazy variant when possible).  Feel free to experiment.

**Comment by Huy-Ngo** [comment]
I will rename the function to avoid confusion. 

> from `alure.AuxiliaryEffectSlot.get_source_send()` you get a vector of `SourceSends`

Ooof, I've done it backwards.

> and `yield` tuples of (source, send)

I thought it's a python thing. It says `yield` is not supported here.

And this remains unresolved:

```
palace.pyx:87:50: Python object type 'Source' cannot be used as a template argument
```

**Comment by McSinyx** [comment]
> It says `yield` is not supported here.

That's OK.  It better if it is, but it does not matter that much.

>     palace.pyx:87:50: Python object type 'Source' cannot be used as a template argument

Could you please push you current code to #21 so I can have a view what's on line 87?

**Comment by Huy-Ngo** [comment]
[That](https://github.com/McSinyx/palace/commit/9474e1f97c470497bf1c751700dfa12824777b47#diff-7c606f8f9d1ea9beec60f818070fee5eR87) was already pushed. I'm going to push another commit with fewer errors (but essentially the same)

**Comment by McSinyx** [comment]
Aight so the error is referring to some kind of incompatibility with (Python object) `Source` used in there.  Since `cdef`, as the name hinted, define C functions (I totally missed that earlier when I talked about `yield`), only C/C++ types are allowed I think.  You could experiment further but if what I'm saying is correct, return `vector[pair[alure.Source, unsigned]]` (note that `SourceSend.mSend` is `ALuinit`) then do the ugly `impl` assignment hack in the Python method.

**Comment by Huy-Ngo** [comment]
Should I use `cpdef` instead, so it can be called in the Python method (`source_sends`)? I think writing the function is done but I'm not sure how to call it now.

> do the ugly `impl` assignment hack in the Python method

If you mean `impl.unpack_source_sends` then it's say `impl` is undeclared name not builtin. `self.impl.unpack_source_sends` is even more wrong because that's not a method of `AuxiliaryEffectSlot`.

**Comment by McSinyx** [comment]
Since the function is not to be used elsewhere, I believe you can just move the content inside the method.

**Comment by Huy-Ngo** [comment]
I'm not sure how to convert C++ object to python object though. I know that using `Source(m_source)` is wrong (see `palace.pyx:1323:33` or search for `FIXME`), but just `m_source` gives the same error. Googling "convert cython object to python object" doesn't help...

**Comment by McSinyx** [comment]
My suggestion would be something like
```python
for source_send in self.impl.get_source_sends():
    source = Source(None)
    source.impl = source_send.source  # die Hungarians, die
    yield source, source_send.send
```

I'm not very certain about the first line: you might (or might not) need to declare `cdef SourceSend source_send` tho.

**Comment by Huy-Ngo** [comment]
Thanks. Such a simple solution solved the problem. Now I close this (should've included that keyword in the commit message though...)
