### ISSUE TITLE
Implement Effect and relevant methods

### ISSUE THREAD

**Issue by Huy-Ngo** [McSinyx/palace#24]
Since this method uses unimplemented class `Effect`, I will leave this until @9a24f0 finish it.

**Comment by McSinyx** [comment]
Gentle ping: what's up @9a24f0?  Is there anything we can do to help you move forward (with this, with life, with your anime addiction)?

**Comment by McSinyx** [comment]
Gentle pong: @9a24f0, you have to communicate.  There's no way we can move this forward with you not saying anything.  If there is any trouble(s), you have to state them.

**Comment by McSinyx** [comment]
@9a24f0:  You may use [data classes](https://docs.python.org/3/library/dataclasses.html) as user interface for reverb and chorus properties if you want to, although that'll require Python 3.7+.

**Comment by McSinyx** [comment]
Note that `AuxiliaryEffectSlot.apply_effect` is not yet implemented in GH-54.

**Comment by McSinyx** [comment]
See d5cf95c59505daacc78e1ee06165f83c47d7db07.
