### ISSUE TITLE
Context managers managing Context does not manage contexts contextually

### ISSUE THREAD

**Issue by McSinyx** [McSinyx/palace#30]
For example,
```python
with context_foo:
    # The current context is context_foo.
    with context_bar:
        # The current context is context_bar.
    # The current context is None, while it should be context_foo.
```

This can be easily fixed by caching the current context (`Context::getCurrent`) and return to it instead of making `None` the current on `__exit__`.  PR with test included is welcome.

**Comment by Huy-Ngo** [comment]
`Context::getCurrent` returns a C++ context and I'm not sure how to convert that into Python context, so I made a stack of contexts and pop as they are destroyed. I'm not sure if that work, because 11 tests failed when I check with tox, though none of them are called directly by Context class.

**Comment by McSinyx** [comment]
To get the Python `Context`, you can use the same idiom in `Source.group`.

Edit: That'd be for the module-level function `current_context` (it'd be nice to have it as a static property, but I don't think Python support such thing), which should be included in the PR as well I think.  But for the fix itself, a `cdef` of the `alure.Context` as `previous` or any name you think would suit the situation would do the job (of course you'll need to test that).

**Comment by Huy-Ngo** [comment]
Isn't `Context.current_class` a static property if I I declare it in the class ([class property](https://stackoverflow.com/questions/68645/are-static-class-variables-possible-in-python))?

Also the test will be included in [test_source.py](https://github.com/McSinyx/palace/blob/context-mng/tests/test_source.py) right?

Edit: Apparently class variable vs instance variable as mentioned in the SO link is only true for primitive datatypes, not abstract datatypes like list (*), but I still don't see why we shouldn't use it as static variable. Is it less secure because any instance can change class variable value??

(*): E.g.

```python
class Foo:
    x = 5
    arr = []

bar = Foo()
bar.x = 2
bar.arr.append(3)

>>> Foo.x
5
>>> Foo.arr
[3]
```

**Comment by McSinyx** [comment]
My use of the term `property` refers to the builtin `property` decorator, which gives a method a attribute interface, e.g.
```python
class Foo:
    @staticmethod
    @property
    def bar(): return 42
```

Of course the above `Foo.bar` does not work because `property` binds (or will bind to be precise) but `staticmethod` does not.

You could make it a static method, but the idea never appeals to me, esp. when all classes are too crowded, so just make current context a module-level function, which pars with `use_context`.

**Comment by McSinyx** [comment]
> Apparently class variable vs instance variable as mentioned in the SO link is only true for primitive datatypes, not abstract datatypes like list

That's not exactly correct.  Both `x` and `arr` are bound to the class (not the object), and thus cannot be changed from the object reference.  However, since `list` is mutable, the inner representation can be modified (see #7).

> Also the test will be included in test_source.py right?

It should be in `tests/test_context.py` I believe.

**Comment by Huy-Ngo** [comment]
What is `alure::getCurrent()` supposed to return, if there is no context used? Is it a null pointer (or `None` in Python)?

**Comment by McSinyx** [comment]
I believe so, but you can read alure's source to be sure.

**Comment by Huy-Ngo** [comment]
So... I guess this is probably solved, but probably not the way you like - I don't use `alure::getCurrent` and I make `current_context` to be a static method instead of make it a module-level function and use `previous` for caching previous context.

But it works (at least according to the tests).
