### ISSUE TITLE
Port examples from Alure and OpenAL Soft

### ISSUE THREAD

**Issue by McSinyx** [McSinyx/palace#39]
Since palace deals with audio device, which is quite inconsistent across different kinds of hardware and platform, unit tests are not sufficient.  Furthermore, examples are very helpful for users to get started using the library.

Here is the list of examples to be ported (without palace name prefix), along with pointers to upstream version:
- [x] info: [openal-info](https://github.com/kcat/openal-soft/blob/master/utils/openal-info.c)
- [x] event: use MessageHandler
- [x] hrtf: [alure-hrtf](https://github.com/kcat/alure/blob/master/examples/alure-hrtf.cpp) and [alure-play3d](https://github.com/kcat/alure/blob/master/examples/alure-play3d.cpp)
- [x] reverb: [alure-reverb](https://github.com/kcat/alure/blob/master/examples/alure-reverb.cpp)
- [x] stdec: use Python standard libraries to decode AIFF/AIFC, Sun AU and WAV
- [x] tonegen: [altonegen](https://github.com/kcat/openal-soft/blob/master/examples/altonegen.c)
- [ ] loopback: [alloopback](https://github.com/kcat/openal-soft/blob/master/examples/alloopback.c)
- [x] latency: [allatency](https://github.com/kcat/openal-soft/blob/master/examples/allatency.c)

Feel free to add any example you find interesting to the list.

**Comment by McSinyx** [comment]
I almost forgot, @Huy-Ngo please edit the `play` example to use `MessageHandler` to print the audio file information, i.e. to replace these lines:
```python
print(f'Playing {filename} ({buffer.sample_type},',
      f'{buffer.channel_config}, {buffer.frequency} Hz)')
```

Edit: this has been done in 308671bc4033e79bcddb50171eab78a9ccbba11c.

**Comment by McSinyx** [comment]
Since @Huy-Ngo is pretty comfortable with the codebase, I believe perse may lead this just fine (after 0.1 release of course).  That being said, perse can assign others to do tasks that otherwise would take too much time.

Edit: to @9a24f0 also, during 0.2 roadmap I may get a little more busy than usual, so basically I'll mostly dedicate my time fixing discovered bugs; and the only way to discover more bugs is to write more tests, in the form of either unit or functional tests, with the later being examples.

**Comment by Huy-Ngo** [comment]
> per

Is this one of those exotic neutral third person pronoun or something? I goes by `he` btw so don't be afraid of me accusing you of assuming gender lol.

**Comment by McSinyx** [comment]
> Is this one of those exotic neutral third person pronoun or something?

Yes.  Edit: [should have been *perse*](https://stallman.org/articles/genderless-pronouns.html) (this sounds like *arse* tho).

> I goes by he btw so don't be afraid of me accusing you of assuming gender lol.

After this public statement I think I'm not afraid anymore.

**Comment by McSinyx** [comment]
@Huy-Ngo, you might want to start working on this now.

**Comment by Huy-Ngo** [comment]
Just realized the other examples are from OpenAL soft and not alure. Do you know what are those [lengthy static declaration](https://github.com/kcat/openal-soft/blob/master/examples/allatency.c#L41-L52)?

**Comment by McSinyx** [comment]
No idea.  The purpose of that is to report the [latency](https://mcsinyx.github.io/palace/html/reference.html#palace.Source.latency) of the source every 10 ms though.

**Comment by Huy-Ngo** [comment]
10ms? That would flood your screen.

I mean, do you want it to be like that, or do you prefer it to just update the line like with `pretty_time` in other examples?

**Comment by McSinyx** [comment]
> 10ms? That would flood your screen.

Not if you carriage return and flush the stream.  BTW this is what printed in the linked example:
```python
print(f'Offset: {round(source.offset_seconds)} - Latency: {source.latency // 10**6} ms', end='\r', flush=True)
```

Edit:  Sometimes I wonder if my use of f-string is abusive, i.e. the following would do the same thing:
```python
print('Offset:', round(source.offset_seconds), '-', 'Latency:', source.latency//10**6, 'ms', end='\r', flush=True)
```

**Comment by Huy-Ngo** [comment]
> info: openal-info (incomplete)

What info is missing here? As far as I'm aware:
- OpenAL info
- Available resamplers
- Available effects

Is there anything missing? Also where can I get OpenAL info?

**Comment by Huy-Ngo** [comment]
By the way, I don't think I quite understand what the loopback example does. Can you do this one?

**Comment by McSinyx** [comment]
If you have openal-soft installed there should be `openal-info` in your PATH.
<details><summary>The following is the output from my end</summary><p>

```console
$ openal-info
Available playback devices:
    Built-in Audio Analog Stereo
    FFT based equalizer on Built-in Audio Analog Stereo
Available capture devices:
    Built-in Audio Analog Stereo
    Monitor of Built-in Audio Analog Stereo
    Monitor of FFT based equalizer on Built-in Audio Analog Stereo
Default playback device: Built-in Audio Analog Stereo
Default capture device: Built-in Audio Analog Stereo
ALC version: 1.1

** Info for device "Built-in Audio Analog Stereo" **
ALC version: 1.1
ALC extensions:
    ALC_ENUMERATE_ALL_EXT, ALC_ENUMERATION_EXT, ALC_EXT_CAPTURE,
    ALC_EXT_DEDICATED, ALC_EXT_disconnect, ALC_EXT_EFX,
    ALC_EXT_thread_local_context, ALC_SOFT_device_clock, ALC_SOFT_HRTF,
    ALC_SOFT_loopback, ALC_SOFT_output_limiter, ALC_SOFT_pause_device
Available HRTFs:
    default-44100
    default-48000
    Built-In 44100hz
    Built-In 48000hz
OpenAL vendor string: OpenAL Community
OpenAL renderer string: OpenAL Soft
OpenAL version string: 1.1 ALSOFT 1.19.1
OpenAL extensions:
    AL_EXT_ALAW, AL_EXT_BFORMAT, AL_EXT_DOUBLE, AL_EXT_EXPONENT_DISTANCE,
    AL_EXT_FLOAT32, AL_EXT_IMA4, AL_EXT_LINEAR_DISTANCE, AL_EXT_MCFORMATS,
    AL_EXT_MULAW, AL_EXT_MULAW_BFORMAT, AL_EXT_MULAW_MCFORMATS, AL_EXT_OFFSET,
    AL_EXT_source_distance_model, AL_EXT_SOURCE_RADIUS, AL_EXT_STEREO_ANGLES,
    AL_LOKI_quadriphonic, AL_SOFT_block_alignment, AL_SOFT_deferred_updates,
    AL_SOFT_direct_channels, AL_SOFTX_events, AL_SOFTX_filter_gain_ex,
    AL_SOFT_gain_clamp_ex, AL_SOFT_loop_points, AL_SOFTX_map_buffer,
    AL_SOFT_MSADPCM, AL_SOFT_source_latency, AL_SOFT_source_length,
    AL_SOFT_source_resampler, AL_SOFT_source_spatialize
Available resamplers:
    Nearest
    Linear *
    Cubic
    11th order Sinc
    23rd order Sinc
EFX version: 1.0
Max auxiliary sends: 2
Supported filters:
    Low-pass, High-pass, Band-pass
Supported effects:
    EAX Reverb, Reverb, Chorus, Distortion, Echo, Flanger, Frequency Shifter,
    Pitch Shifter, Ring Modulator, Autowah, Compressor, Equalizer,
    Dedicated Dialog, Dedicated LFE
```

</p></details>

**Comment by Huy-Ngo** [comment]
Unfortunately, I don't have OpenAL Soft, and I'm having problems installing it. It seems to lack some dependencies (SDL2, ZLIB, MySOFA, ...). Somehow `palace-info.py` says OpenAL Soft is a basic device though.

**Comment by McSinyx** [comment]
> Unfortunately, I don't have OpenAL Soft, and I'm having problems installing it. It seems to lack some dependencies (SDL2, ZLIB, MySOFA, ...)

Should be in your distro repo (you already had it to compile alure).  Who has time to compile such thing LOL.

**Comment by Huy-Ngo** [comment]
Hmm that's strange then. It can't recognize `openal-info` as a command, since it's not in my `$PATH` (tried to print them all out). I have no idea how to get EFX info either, so maybe I'll just add the info about resamplers.

**Comment by McSinyx** [comment]
Sorry, on Debian(-based distros too?) it is in a dedicated package name `openal-info`.

**Comment by Huy-Ngo** [comment]
Oh I see, got it. Though, since that prints everything already, what would be the point of `palace-info.py`?

**Comment by McSinyx** [comment]
> what would be the point of `palace-info.py`?

Like other examples, to demonstrate the usage of palace (i.e. how to do some particular thing).  Have you figured out how to list available extensions yet btw?

**Comment by Huy-Ngo** [comment]
From palace, no. I think we can't do it without implementing some new functions.

**Comment by McSinyx** [comment]
Regard running examples in our CI, `testenv.commands` in `tox.ini` is the place to put the examples.  I wonder where should we place the audios and the wrapper script (in Python from cross-platform compatibility) though.  My first though is to move `tests` into `tests/unit` and put the new functional tests in `tests/examples`.

**Comment by Huy-Ngo** [comment]
Can't we run it on two different directories?

I think that placement would be clear, though.

**Comment by McSinyx** [comment]
> Can't we run it on two different directories?

What do you mean by *it*?  Also I was totally in some weird mental condition when I wrote the above comment, should have been `tests/functional`.  To clarify, it should only include the audios and the script with `subprocess` calls.  Or not.  Maybe it's better to symlink the examples there to avoid the `../..` thing.

**Comment by McSinyx** [comment]
Also to @9a24f0, the audios might need to reside in `tests/` and there (absolute) paths might need to be fixturized by a `conftest.py`, since our unit tests for buffers and streams (decoders) also require resources.

**Comment by 9a24f0** [comment]
erm.... what are "paths"...

**Comment by McSinyx** [comment]
[LMWTFY](https://en.wikipedia.org/wiki/Path_(computing)) @9a24f0

**Comment by 9a24f0** [comment]
LOL, that's not what I mean. Since we have only 1 `src/`, so wdym by specify path o.O

**Comment by McSinyx** [comment]
Please quote my sentence you're referring too, I'm not sure what you're talking about.

**Comment by 9a24f0** [comment]
> Also to @9a24f0, the audios might need to reside in `tests/` and there (absolute) paths might need to be fixturized by a `conftest.py`

this one o.O

**Comment by McSinyx** [comment]
Ooh right, so according to the plan above,
* Unit tests will be moved from `tests/` to `tests/unit/`
* Audio will be in `tests/`.  In this same dir, we create a `conftest.py` with a fixture of `basename(__file__)/audiofile` (use `os.path.{join,basename}` for this)
* Buffer unit test, i.e. in `tests/unit/test_buffer.py`, can access to the audio paths as the form of fixture, e.g. `def test_cache(context, mp3): cache([mp3])`
* Functional tests can also access the same audios, but run the examples instead, i.e. use `subprocess` to call, e.g. `[sys.executable, 'palace-hrtf.py', flac]`

**Comment by 9a24f0** [comment]
oof, noted. May I will ask more ab this several times

**Comment by 9a24f0** [comment]
@McSinyx do you miss the lecture today

**Comment by McSinyx** [comment]
LMAO thanks.

**Comment by Huy-Ngo** [comment]
As discussed in #83, The loopback example wouldn't be ported since that's beyond our ability.
