### ISSUE TITLE
Handling of C++11 std::chrono durations

### ISSUE THREAD

**Issue by McSinyx** [McSinyx/palace#4]
Many time values in APIs in alure are exposed as a [chrono durations (convenience typedefs)](https://en.cppreference.com/w/cpp/header/chrono).  Declaration of such nested namespace might be similar to [that of enum class here](https://github.com/McSinyx/archaicy/commit/e8bb1fe76f97b0da3279ed2bb6c8d60e2e9209ff#diff-52e119e96f801a14b1ac71e2bada8063R41-R64).

The real issue is how we should expose such data.  I believe `nanoseconds`, `seconds`, etc. are used a to makes the C++ API self-documenting, so should we

* Simply use Python `int` and document the unit as docstrings, or
* Use the standard `datetime`?

**Comment by 9a24f0** [comment]
i don't have any idea about standard `datetime` is. But the upper one seems that it can't handle `nanoseconds`

**Comment by McSinyx** [comment]
`datetime` is a Python standard module (just `help` yourself on that).  Both solutions will get the inner numeric representation using [`duration::count`](https://en.cppreference.com/w/cpp/chrono/duration).

**Comment by McSinyx** [comment]
Reopening this since obviously it's not solved (yet).
