### ISSUE TITLE
Finish Context and Source

### ISSUE THREAD

**Issue by McSinyx** [McSinyx/palace#44]
Try to do as many TODO as you are able to do, gradually.

**Comment by Huy-Ngo** [comment]
Are these lines included in this issue?

https://github.com/McSinyx/palace/blob/308671bc4033e79bcddb50171eab78a9ccbba11c/src/palace.pyx#L149-L150

**Comment by McSinyx** [comment]
Yep, and please implement them as part of `{use,current}_context` using optional parameters (`thread` or something like that).

**Comment by Huy-Ngo** [comment]
I should write `thread: Optional[bool]` in the function arguments instead of `thread=False` right? Or is it `thread: bool=False`?

**Comment by McSinyx** [comment]
`thread: bool = False`, [Optional](https://docs.python.org/3/library/typing.html#typing.Optional) is a really misleading name IMHO.

**Comment by McSinyx** [comment]
Just a friendly reminder that this isn't finished.

**Comment by McSinyx** [comment]
~~I'm finishing the source it make effects work.~~  nvm go on we already got aux send defined.

**Comment by McSinyx** [comment]
Gentle ping, @Huy-Ngo
