### ISSUE TITLE
Test coverage

### ISSUE THREAD

**Issue by McSinyx** [McSinyx/palace#46]
The higher the coverage the better, but we should aim for at least 69%.  Since @9a24f0 is going to do an entire course in QA anyway, please lead this.  Feel free to assign others if you feel that you cannot write all the tests.

**Comment by McSinyx** [comment]
@9a24f0, I suggest you should start studying how our tests work and start writing some.  One commit a day would be great, even if each is just adding a testing function.

**Comment by 9a24f0** [comment]
@McSinyx, Can you give me some coach on that, some reference should be fine.  Idk I can do things atvm.

**Comment by McSinyx** [comment]
Please make sure that you read through the pytest's documentation, esp. the fixtures part.  Then start by completing the existing tests in `tests/` by adding the code that execute and check the behaviors of stuff that are not checked.

By running `tox` you should be able to see the coverage percentage; in case you want to speed up test time, install palace using `CYTHON_TRACE ./setup.py install --user`---that will give you the palace runtime with line trace for coverage report.

**Comment by McSinyx** [comment]
Gentle ping, @9a24f0!

**Comment by McSinyx** [comment]
@9a24f0, you might want to start working on this now.

**Comment by McSinyx** [comment]
Gentle ping, @9a24f0.

**Comment by Huy-Ngo** [comment]
@9a24f0 Which class are you going to test this week, so that I'm gonna test another class?

**Comment by McSinyx** [comment]
I figured that the statistics provided by coverage seems to be incorrect (e.g. unit tests for Source reaches 100%, but of what?).  Just ignore it for now.

**Comment by Huy-Ngo** [comment]
Wait, do you mean there are something not tested yet in Source?

**Comment by Huy-Ngo** [comment]
Hmm now that I think of it, maybe 100% is probably not coverage, but the progress of testing. Since source is the last test, it's 100%.

**Comment by McSinyx** [comment]
You're right, somehow the average of these percentage is (coincidentally) equal to the coverage, which made me incredibly confused.

BTW I've disabled automated testing for macOS (yay!), due to in-timeout-able freezes.  Should be solved later on.

**Comment by McSinyx** [comment]
As of c59d0ec1696c65e887f8645e449f7ee03add5fe2, the coverage is now 80%, so this is no longer blocking 0.2 release.  However, it's worth noting that we still want to push the figure as close to 100% as we can.  Edit: unassigned people to shift focus to more urgent issues.

**Comment by McSinyx** [comment]
@9a24f0, I just want to remind you that if you want to use the test suit of this repo to apply the principle of testing you learn from the QA course, feel free to do so.  This includes adding, refactoring and moving all kind of tests.

**Comment by McSinyx** [comment]
*Moved to https://todo.sr.ht/~cnx/palace/2*
