### ISSUE TITLE
Testing new functions in Context class

### ISSUE THREAD

**Issue by Huy-Ngo** [McSinyx/palace#48]
I find that the new functions that are being implemented in [`ctx-fin`](https://github.com/McSinyx/palace/tree/ctx-fin) are hard to test.

For example, [write-only](https://github.com/McSinyx/palace/blob/1f482e3676ed82b5329612e9c1c64b6e0bfbe9ee/src/palace.pyx#L537) and [read-only](https://github.com/McSinyx/palace/blob/1f482e3676ed82b5329612e9c1c64b6e0bfbe9ee/src/palace.pyx#L512) properties, or functions [without documentation](https://github.com/McSinyx/palace/blob/1f482e3676ed82b5329612e9c1c64b6e0bfbe9ee/src/palace.pyx#L472). I'm not even sure if they need to be tested.

**Comment by McSinyx** [comment]
For read-only, we can test for default values; for write-only we can do test write, which mostly are only to ensure we have the palace-alure bridge working.  I don't think that is enough for correctness-assurance tho.

For stuff without documentation, try to read the source and figure out what it does.

Edit: This is relabeled as *discussion* instead to reserve *question* for our downstream usage.

**Comment by McSinyx** [comment]
I'm closing this in favor of discussion meta approaches for (white-box) testing in GH-46.
