### ISSUE TITLE
Writing software requirements specification (SRS)

### ISSUE THREAD

**Issue by Huy-Ngo** [McSinyx/palace#55]
As of now I found three layout for SRS (IEEE 830) from 3 sources:

- [Wikipedia](https://en.wikipedia.org/wiki/Software_requirements_specification)
- [A lecture from uOttawa](https://www.cin.ufpe.br/~if716/arquivos20162/03-IEEE-830)
- [An example on StuDocu](https://www.studocu.com/row/document/addis-ababa-university/software-engineering/mandatory-assignments/ieee-830-1998-standard-srs-document/1981874/view)

Please discuss the documentation layout here and decide on how to write the document.

**Comment by Huy-Ngo** [comment]
I'm writing an outline based on the [teacher's link](http://se.inf.ethz.ch/old/teaching/2010-S/0284/Slides/SampleRequirementsSpec.pdf) on [google doc](https://drive.google.com/open?id=1yJyRJiQZA8G8SlSWWsL-ac_T371vZiILx9gyf5qgTLw). Please help when you can.

**Comment by McSinyx** [comment]
Please cooperate it into our documentation (you can edit GH-18 and add an entry to it for the matter of completeness).  However, I wonder, how much different the specification and reference are?  Can we do 2-in-1?  Note that the current reference uses `automodule`, mainly to test Sphinx compatibility.  We'll need to make it some kind of proper documentation with some (minimal) human language instructions.

To ones outside of our team reading this, we try to cooperate this project into an bachelor software engineering course.  I am not certain if a typical downstream dev is going to go through the spec for any reason in this specific case though.  The purpose the SRS (per an private discussion with our lecturer) is to (1) make sure we know what an SRS is and probably know how to write it and (2) to help users on using the library.  I feel, however, a downstream developer would benefits much more from proper documentations and tutorials.

There are also a few technical concerns about the specification though.  Our API almost completely rely on alure 2 *design decisions*, i.e. we are not in the position to make major choices.  The API of alure 2 is not considered stable by its author either.  Furthermore, none of us is a qualified technical writer, thus the resulting specification may not be able serve its purpose, while the amount of time and effort spent on it will not be insignificant. 

I not sure what are your (@Huy-Ngo and @9a24f0) takes on this.  I might have missed something really important, or I might have not.  If the latter is true, please edit the current reference to include proper inter-module explanation:
* Split the automodule thing into multiple pages for
    1. Device and related functions
    2. Context, attributes for context creation, listener and message handler
    3. Decoder, file I/O and buffer
    4. Source and source group
    5. Effect and auxiliary effect slot
* Each class would need to interact with some other classes.  Our job is to make it clear to the users, with extra explanation if needed.

**Comment by Huy-Ngo** [comment]
It is important that we spend more time for development than technical writing, especially when we're already late on deadline. So, I agree with you, but we still need to finish the task given, I believe, so my suggestion is keeping the technical things minimal on this SRS document, and link it to our API reference.

For example, for installation instruction, we can write only:

> Palace can be installed from PyPI or from source code. For detailed instruction, please see our official [document page](https://mcsinyx.github.io/palace/html/installation.html).

...or something like that.

**Comment by McSinyx** [comment]
My main concern over this (SRS) is that in order for our effort to make any sense, we'd need to follow a somewhat formal and quite detailed structure.  If you insist on this, add an entry to our documentation branch (`gh-pages` for now) and at least draft a structure.  I'll try to help out when time allows but if you do incremental writing it'd be difficult to know which part you're working on to avoid.

BTW if I were you, I'd prioritize GH-56 over this, since we ain't officially document the design anywhere.  And remember to finish GH-44 ASAP for 0.1 to see the light of day.

**Comment by Huy-Ngo** [comment]
Ok then, let's settle that we're going to use the reference in place of SRS. As for GH-44 I thought you said there were something with integration so I wait until you finish things on master. Knowing it's ready I'm going to continue next week. I'm closing this issue for now.

**Comment by McSinyx** [comment]
> Ok then, let's settle that we're going to use the reference in place of SRS.

Hip hip hooray!

> As for GH-44 I thought you said there were something with integration so I wait until you finish things on master.

I think I told you not to let your branch diverges to far to avoid conflicts/integration hell.

**Comment by Huy-Ngo** [comment]
> I think I told you not to let your branch diverges to far to avoid conflicts/integration hell.

Oof, it's me skimming and not reading carefully again.

As for using the reference technically that would be user documentation, not SRS, but to quote the teacher himself, we only need to apply 4-5/10 things being taught 🙂

**Comment by dinhanhx** [comment]
Have read
