### ISSUE TITLE
Writing software design description (SDD)

### ISSUE THREAD

**Issue by Huy-Ngo** [McSinyx/palace#56]
I found [a very detailed example](https://senior.ceng.metu.edu.tr/2015/musinspro/MusIns-Pro_SDD.pdf). Also [this one](http://cengproject.cankaya.edu.tr/wp-content/uploads/sites/10/2017/12/SDD-ieee-1016-2009.pdf)

Please discuss the documentation layout here and decide on how to write the document.

**Comment by McSinyx** [comment]
Not sure about you guys, but I don't think I have the time or the mental space to (help) write a formal one.  My suggestion is to briefly note the central principals, including, but not limited to
1. How to wrap C++ functionalities (https://github.com/McSinyx/palace/issues/2#issuecomment-571610377)
2. How to adapt C++ API into modern Python:
    * How to expose getters/setters
    * How to handle enums (GH-47)
    * How to ensure heap data reallocation (try-finally, i.e. context manager)
3. How to wrap C++ interface

GH-18 has been edited to include this section.

**Comment by Huy-Ngo** [comment]
I've tried to read the example and I'd say that I don't have the energy to write such thing within one or two weeks either. Let's be pragmatic and write something more minimal instead.

In addition to your three points, I think we should also include describing classes and interactions in this.

**Comment by McSinyx** [comment]
> classes and interactions

can be documented in the reference IMHO.  The others are done now so I'm closing this.

**Comment by dinhanhx** [comment]
Have read
