### ISSUE TITLE
Where to put methods for async buffers?

### ISSUE THREAD

**Issue by Huy-Ngo** [McSinyx/palace#57]
One of the TODO's  in `Context` is for async buffers. I suppose this includes three functions, `precache_buffers_async`, `create_buffer_async_from` and `find_buffer_async`. I suppose that the later two should be included written in `Buffer` constructor like their synchronous counterparts?

**Comment by McSinyx** [comment]
Only `precache_buffers_async` is within the scope of GH-44, the others are supposed to be handled by GH-37.  Sorry for not noting this earlier.

**Comment by Huy-Ngo** [comment]
Since other functions are handled by other issues, should I remove the TODO's in class Context or leaves it there?

**Comment by McSinyx** [comment]
Yes, it's already documented as TODO in Buffer definition I think.
