### ISSUE TITLE
Lifetime of alure2-typeviews for asynchronious calls

### ISSUE THREAD

**Issue by Huy-Ngo** [McSinyx/palace#59]
Currently the use of `StringView` as in  7744c37 and  151b276 allows the code to compile, but it causes segfault when running.

This is because the views outlive the actual data. This can be fix by create `new` objects, but it will cause memory leaks, unless you can figure out on how to use smart pointers for this purpose. ([original](https://github.com/McSinyx/palace/commit/555875c30df36d92c6749c03f3601a580116617b#commitcomment-37982004))

**Comment by McSinyx** [comment]
One way to work around this is to store the data as an attribute of `Context`, so the views can view the data that still exist in the memory.  At `Context.destroy` we can safely remove it so no leak will occur.

**Comment by Huy-Ngo** [comment]
So it's something like

```python
cdef class Context:
    cdef vector[alure.StringView] precached_buffers
    def destroy(self) -> None:
        self.precached_buffers.clear()
        self.impl.destroy()
    def precache_buffers_async(self, names: List[str]) -> None:
        cdef vector[string] std_names = names
        cdef vector[alure.StringView] alure_names
        cdef alure.StringView alure_name
        for name in std_names:
            alure_name = new alure.StringView(name)
            alure_names.push_back(<alure.StringView> name)
            self.precached_buffer.push_back(alure_name)
        self.impl.precache_buffers_async(alure_names)
```

**Comment by Huy-Ngo** [comment]
Hmm... cannot use `new alure.StringView(name)`. It says that it expects 0 argument. How else could I assign it a value if it's view only?

That's weird because `StringView("some string here")` is used in alure examples.

Edit: Fixed by writing a constructor definition in alure.pxd. Successful build, but I'm not sure it works.

**Comment by Huy-Ngo** [comment]
I'm not sure this is fixed. Please confirm this and close this issue.

**Comment by McSinyx** [comment]
Closing this since the real issue due to `MessageHandler.buffer_loading` for the same reason mentioned in GH-10.
