### ISSUE TITLE
Document values for multi-value setters

### ISSUE THREAD

**Issue by Huy-Ngo** [McSinyx/palace#64]
For multi-value setters, the variables and its order are quite unclear:

For example:

* [Here](https://github.com/McSinyx/palace/tree/e747159161896da2bf7685cb08cb67cee12d93d7/src/palace.pyx#L1677-L1681) it's unclear what the int is for.
* [Here](https://github.com/McSinyx/palace/tree/e747159161896da2bf7685cb08cb67cee12d93d7/src/palace.pyx#L848-L849) it's unclear which order is the coordinates (it's x, y, z, but which one is altitude?).
* [Or in the case of the function I'm writing](https://github.com/McSinyx/palace/blob/src-fin/src/palace.pyx#L1675-L1676), it's unclear what are the params in this filter params and what are their order (gain, gain hf, gain lf). 

I'm not sure how we should document these properties to the users.

Edit: use link to commits and reformat.

**Comment by McSinyx** [comment]
We follow numpydoc style, which does not specify how to do this.  For some setters, `Parameters` is used and I think that'd be good enough until we figure out something else.
