### ISSUE TITLE
Test `context.start/endbatch` methods

### ISSUE THREAD

**Issue by 9a24f0** [McSinyx/palace#71]
I have been writing tests for context and there are 2 methods: `context.startbatch` and `context.endbatch` which concerns me because how could we know if the context is suspended or not. Any idea? @McSinyx and @Huy-Ngo

**Comment by McSinyx** [comment]
First of all, they are neither properties nor classes but methods :smile: 

About suspension, see [this](https://github.com/kcat/openal-soft/blob/a895709b6f67586d4aec3c6f0b276b01899cae86/docs/env-vars.txt#L70), which I don't know if it'll help testing tho.

About batching, alure set `ContextImpl::mIsBatching`, which is only used by `ContextImpl::getBatcher`, whose result isn't use any where within alure.  I'm not sure what kind of magic is involved there, or simply it's awaiting proper implementation of some missing feature.  Either way, I think for now you'll only need to test if the two methods does not crash.

**Comment by 9a24f0** [comment]
LOL i was looking for a word to call them
so it's kinda like this?
```
def test_batch(device):
    "Test if batch works properly."
    with Context(device) as context:
        context.start_batch
        context.end_batch
```

**Comment by McSinyx** [comment]
> they are neither properties nor classes but methods

and should be called as such.   Moreover, it's a better practice if you can give each there own test.

**Comment by McSinyx** [comment]
I'm closing this now since there's not really anything these methods really do to be really tested.  Feel free to reopen if there's any new problem arises.
