### ISSUE TITLE
Examples hang on macOS on Travis CI

### ISSUE THREAD

**Issue by McSinyx** [McSinyx/palace#81]
Travis tests for macOS [308.1](https://travis-ci.com/github/McSinyx/palace/jobs/321760933) and [308.2](https://travis-ci.com/github/McSinyx/palace/jobs/321760934) are failing because the examples runs for way too long (10+ minutes).  Optimization ideas include:

* Use shorter audios, a few dozens ms would be ideal
* Parameterize tests and run them in parallel
* Avoid exhaustive input set for playback

I'll take care of this one myself, collaborators can jump in to help but please focus on GH-46 and GH-39 and try to finish them before the next weekly release.

**Comment by Huy-Ngo** [comment]
In addition, the tonegens example now are generating 1-second long audio by default. We can easily reduce that.

**Comment by McSinyx** [comment]
Since alure (and thus palace) is not thread-safe, unfortunately we cannot run tests in parallel :disappointed:  They should pass Travis time limit just fine though.

**Comment by McSinyx** [comment]
Reopen because the original issue is still not solve.  Build [309.1](https://travis-ci.com/github/McSinyx/palace/jobs/322161211) for instance seems to hangs indefinitely.  Could be because there's no support for audio on the macOS VM.  If that's so, we can allow these tests to fail.
