### ISSUE TITLE
The design of "reverb_properties" and "chorus_properties" of class Effect is hard to use

### ISSUE THREAD

**Issue by Huy-Ngo** [McSinyx/palace#85]
To set a value for this property, it requires you to set all 26 effect properties. This makes it harder to modify only one of those properties (and also harder to test). In addition, which properties are included in the dict value is unknown to the user, unless they read the source code.

Should we:
- set a default value for it, and/or
- make it different properties for an Effect instance?

The same problem for "chorus_properties", but it has less properties in the dict value.

**Comment by McSinyx** [comment]
I've been (intentionally) ignoring this for quite a while now, thank you for bringing it up tho :smile:  For GH-84 just finalize the tests for other methods except `reverb*` and `chorus*` to avoid stalling on it for too long, I'll figure something out and add tests for the new thing as I implement it.

Briefly about the idea (to gather some opinion from you if any), `alure::EffectImpl` as a `mType` pointing to either reverb or chorus, i.e. the two effects are mutually exclusive, so I think I can derive from `palace.Effect` to make the thing less confusing.

**Comment by Huy-Ngo** [comment]
So, when we initialize an effect, it's set to either reverb or chorus, am I understanding it correctly?

**Comment by McSinyx** [comment]
Well that's close
```c++
class EffectImpl {
    ContextImpl &mContext;
    ALuint mId{0};
    ALenum mType{AL_NONE};
```
but yes, through out its lifetime, an effect is

> set to either reverb or chorus

**Comment by McSinyx** [comment]
LOL I use Python to write Python
![2020-04-25T17:29:31](https://user-images.githubusercontent.com/13689192/80277683-e048fa80-871a-11ea-91df-bb4f574a4213.png)

**Comment by McSinyx** [comment]
LOL [I use Python to make Python](https://redd.it/g7tn3v)
```python
PROPERTIES = ('density', 'diffusion', 'gain', 'gain_hf', 'gain_lf',
              'decay_time', 'decay_hf_ratio', 'decay_lf_ratio',
              'reflections_gain', 'reflections_delay', 'reflections_pan',
              'late_reverb_gain', 'late_reverb_delay', 'late_reverb_pan',
              'echo_time', 'echo_depth',
              'modulation_time', 'modulation_depth', 'air_absorption_gain_hf',
              'hf_reference', 'lf_reference', 'room_rolloff_factor')
TEMPLATE = """
    @property
    def {0}(self) -> float:
        return self.properties.{0}

    @{0}.setter
    def {0}(self, value: float) -> None:
        self.properties.{0} = value
        self.impl.set_reverb_properties(self.properties)
        self.slot.apply_effect(self.impl)
"""
print(*map(TEMPLATE.format, PROPERTIES), sep='')
```

**Comment by McSinyx** [comment]
> I'll [...] add tests for the new thing as I implement it.

Welp I lied about that, also it'd be better to see if it's easy enough to understand if I'm not the one testing it.  Edit: for leisure reading, see [this](https://kcat.strangesoft.net/misc-downloads/Effects%20Extension%20Guide.pdf).

**Comment by McSinyx** [comment]
Whoever of you'll be doing the test, please fix the regression of that ReverbEffect.gain shadowing BaseEffect.gain (the later can be renamed to `slot_gain` I think).

**Comment by Huy-Ngo** [comment]
Are the reverb/chorus properties intentionally not having docstrings?

**Comment by Huy-Ngo** [comment]
Hmm should I mention this docstring problem in a 1.0 issue? Someone with experience of OpenAL will probably find it familiar, but newcomer will not.

E.g. Why is `waveform` an int? Which int value is corresponding to which waveforms?

**Comment by McSinyx** [comment]
> Hmm should I mention this docstring problem in a 1.0 issue? Someone with experience of OpenAL will probably find it familiar, but newcomer will not.

Sure, personally I don't understand all the properties to document the properly.
