### ISSUE TITLE
Effect properties don't raise ValueError when set to a value out of range

### ISSUE THREAD

**Issue by Huy-Ngo** [McSinyx/palace#88]
Several tests are failing currently. They don't raise `ValueError` where they meant to be.

According to [OpenAL doc](https://kcat.strangesoft.net/misc-downloads/Effects%20Extension%20Guide.pdf) of `AL_EFFECT_EAXREVERB`, (which I suppose `EFXEAXREVERBPROPERTIES` implements), then `reverb_density` should be in range `[0, 1]`, but here it doesn't raise any `ValueError` (or any error, for that matter) if I set it to -1 or 2. This is an example, 14 other tests in `test-eff` are failing for the same reason.

Is this what it means to be? Am I looking at the wrong doc?

**Comment by McSinyx** [comment]
Oops please ignore https://github.com/McSinyx/palace/pull/87#issuecomment-619499784.

Answer to your question, then yes, we should follow the linked specs, by raising errors where it's out of range.

Edit: I haven't actually read the specs before throwing it to you; now looking at it, we can add default values for chorus effect too.

**Comment by Huy-Ngo** [comment]
So it turns out that testing does find some actual issues. It seems that @9a24f0 hasn't done anything this week yet, so I suggest assigning him this task.

**Comment by 9a24f0** [comment]
First of all, I want to apologizes for stalling to project for too long (recently I have mental issues (?) )
I have touched the code base today, much more things happens. So to summarize, as I have looked to it, you guys have:
- Change `Effect` class -> `BaseEffect`
- Implement `EAXReverbproperties and `Chorusproperties` into a class, not a method(property?) like before.
- Write tests for the "old" `Effect` class - yay!

What else did I missed?

Also, I got some problem with pytest in local. At first, I have problem with flake8. And when I turned off flake8, I got some strange error like: 
```
============================================================= ERRORS ==============================================================
___________________________________________ ERROR collecting tests/unit/test_effect.py ____________________________________________
ImportError while importing test module '/home/meteora/Documents/Palace/palace/tests/unit/test_effect.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/unit/test_effect.py:22: in <module>
    from palace import BaseEffect, ReverbEffect, Source
E   ImportError: cannot import name 'BaseEffect'
___________________________________________ ERROR collecting tests/unit/test_source.py ____________________________________________
ImportError while importing test module '/home/meteora/Documents/Palace/palace/tests/unit/test_source.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/unit/test_source.py:26: in <module>
    from palace import Buffer, BaseEffect, Source, SourceGroup
E   ImportError: cannot import name 'BaseEffect'
```
As @Huy-Ngo told me to reinstall things. I have did `pip3 uninstall palace` and reinstall it. After that, I did ` CYTHON_TRACE=1 ./setup.py install --user` to build it. But still have the same problem. However, tox is fine with me, but the wait is toooo long.
Any help? @McSinyx .

**Comment by Huy-Ngo** [comment]
I can't think of a reason why it couldn't import BaseEffect other than that 🤷‍♂️. All what I did to make it work is:

```bash
# palace/
$ ./setup.py clean --all
$ cd ..
$ pip install palace/
```

Hopefully Phong can give you better instruction.

**Comment by McSinyx** [comment]
> First of all, I want to apologizes for stalling to project for too long (recently I have mental issues (?) )

@9a24f0, sorry to hear that, though IMHO it might be better to talk to us than just being silent the whole time.  Life w/o social interaction plus academic pressures might be hard, but it's difficult for us to help if you don't communicate.

As per the pytest thing, first please verify that you're on the right HEAD:
```console
$ git show --summary
commit b2329a1428a4e1f6757ad9b654042e131ae8bc4b (HEAD -> master, origin/master, origin/HEAD)
Author: Ngô Ngọc Đức Huy <duchuy29092000@gmail.com>
Date:   Sun Apr 26 09:49:30 2020 +0700

    Fixing some small mistakes made in 9de664a (#86)
```

If you've updated your system, might be a good idea to check if the python versions of palace and pytest matches to, e.g. for Python 3.7
```console
$ python3.7 setup.py install .
$ CYTHON_TRACE=1 python3.7 -m pytest
```
However with tox succeeded, I believe you haven't uninstalled all palace's versions.  Eggs is quite a confusing thing and the its support is half broken.  To avoid future issues like this, try `CYTHON_TRACE=1 pip3 install .`.

**Comment by McSinyx** [comment]
@9a24f0, I suggest you start with ChorusEffect first, since it's much shorter for the review process to get you the general idea of what I expect.

**Comment by 9a24f0** [comment]
@McSinyx is there other version that wasn't uninstalled by `pip3 uninstall palace`?

**Comment by McSinyx** [comment]
IDK, `pip` should tell you none is left if there's none left.  BTW have you tried specifying Python 3 version as noted above?

**Comment by 9a24f0** [comment]
oh nvm. IDK what mistake did I make but when I do it 2nd time, it works fine o.O

**Comment by 9a24f0** [comment]
@McSinyx related to Computer Network course, would you like to join the same team as in MWC

**Comment by McSinyx** [comment]
<details><summary>DM?</summary><p>

```console
$ dict dm
6 definitions found

From WordNet (r) 3.0 (2006) [wn]:

  DM
      n 1: diabetes caused by a relative or absolute deficiency of
           insulin and characterized by polyuria; "when doctors say
           `diabetes' they usually mean `diabetes mellitus'" [syn:
           {diabetes mellitus}, {DM}]
      2: a metric unit of length equal to one tenth of a meter [syn:
         {decimeter}, {decimetre}, {dm}]

From V.E.R.A. -- Virtual Entity of Relevant Acronyms (February 2016) [vera]:

  DM
         Delta Modulation
         

From V.E.R.A. -- Virtual Entity of Relevant Acronyms (February 2016) [vera]:

  DM
         DeMilitarisierte zone (Firewall)
         

From V.E.R.A. -- Virtual Entity of Relevant Acronyms (February 2016) [vera]:

  DM
         Development Machine (Corel)
         

From V.E.R.A. -- Virtual Entity of Relevant Acronyms (February 2016) [vera]:

  DM
         Disconnect Mode (LAPB)
         

From V.E.R.A. -- Virtual Entity of Relevant Acronyms (February 2016) [vera]:

  DM
         Device Mapper (Linux)
```

</p></details>

**Comment by Huy-Ngo** [comment]
> DM?
He means Computer Network.

Anyway, anything else I can help with?

**Comment by McSinyx** [comment]
> Anyway, anything else I can help with?

See GH-77 and find out if we can make the output C++ compile on MSVC++.

**Comment by Huy-Ngo** [comment]
Maybe I'll look up on that. Still haven't tried to install alure on Windows since.

**Comment by McSinyx** [comment]
> Still haven't tried to install alure on Windows since.

See our `.appvoyer.yml`, that should cover up to alure installation (without Vorbis, Opus, WAV, AIFF and a few other codecs though MP3 and FLAC are builtin so should be fine).
