### ISSUE TITLE
Type and values for some properties in ReverbEffect and ChorusEffect are not intuitive

### ISSUE THREAD

**Issue by Huy-Ngo** [McSinyx/palace#89]
According to [OpenAL doc](https://kcat.strangesoft.net/misc-downloads/Effects%20Extension%20Guide.pdf), `AL_EAXREVERB_DECAYHF_LIMIT` has only two values, `AL_TRUE` and `AL_FALSE`. However, the current type for it is `int`, probably because in C it makes more sense to have int. However, here in Python, I believe it would makes more sense to have it as a boolean property.

**Comment by Huy-Ngo** [comment]
The same goes for `ChorusEffect`'s property `waveform`. It has only two possible value (sin, triangle), so probably it's more intuitive to use enum or string as input.

**Comment by McSinyx** [comment]
Agreed, this should be fixed along with GH-88.

> It has only two possible value (sin, triangle), so probably it's more intuitive to use enum or string as input.

I'd prefer str for this one.
