### ISSUE TITLE
Write a tutorial

### ISSUE THREAD

**Issue by McSinyx** [McSinyx/palace#93]
What to be covered is up to be discussed.  Personally I feel that some deconstructing some examples may gives a good insight on how to use the library.

**Comment by Huy-Ngo** [comment]
>  some deconstructing some examples may gives a good insight on how to use the library

I agree. Based on the HRTF and reverb examples, I can think of this tutorial

- [X] Play an audio
- [X] Move the source
- [X] Use a function to move the source automatically
- [x] Add an effect
  - [x] Default reverb/chorus effect
  - [x] Customized reverb/chorus effect

After that, we can use stdec and tonegen for more advanced uses:

- [ ] Customize decoder
- [ ] Create a decoder for reading generated sounds (Speaking of which, is there a way to save this sound as file?)

**Comment by McSinyx** [comment]
While I agree with you on the proposed contents, I feel the need of elaboration of steps (since after all, it's a tutorial), i.e.
* Create a device
* Create a context
* Branching here to multiple use case as you mentioned

I didn't really think this one really thoroughly though.  See ModernGL tutorial to see what I'm picturing in my mind atm.

> Speaking of which, is there a way to save this sound as file?

The data passed to `MessageHandler.buffer_loading` is a valid raw sound file, I think we can so some minor encoding like adding a header and make it a WAV or sth.  Can't tell w/o trying.

**Comment by McSinyx** [comment]
*Moved to https://todo.sr.ht/~cnx/palace/3*
