### ISSUE TITLE
Linkage problems on Windows

### ISSUE THREAD

**Issue by Huy-Ngo** [McSinyx/palace#99]
[Here](https://ci.appveyor.com/project/McSinyx/palace/builds/32679477/job/aj5r248uddj8ah80) is the output for the next-to-latest build of #98 , which addressed the problem that failed #77.

As can be seen from this log, there is a linkage issue here, and I don't know how to resolve that:

```
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:c:\cibw\python\python.3.6.8\tools\libs /LIBPATH:c:\cibw\python\python.3.6.8\tools\PCbuild\amd64 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB\amd64" "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\LIB\amd64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.18362.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\lib\um\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.18362.0\um\x64" /EXPORT:PyInit_palace build\temp.win-amd64-3.6\Release\src\palace.obj C:/projects/openal-soft-1.20.1-bin/libs/Win64/OpenAL32.lib libalure2-NOTFOUND /OUT:build\lib.win-amd64-3.6\palace.cp36-win_amd64.pyd /IMPLIB:build\temp.win-amd64-3.6\Release\src\palace.cp36-win_amd64.lib
LINK : fatal error LNK1181: cannot open input file 'libalure2-NOTFOUND.obj'
```

[It seems to be](https://github.com/McSinyx/palace/pull/98#issuecomment-624523427) related to some alure library that was linked wrongly.

**Comment by McSinyx** [comment]
Try static linking to see if it works.  Somehow I haven't been able to make that work for GNU/Linux and macOS, while theoretically it should be easy to be done (did not put a lot of effort doing it though).

**Comment by McSinyx** [comment]
May I see the CMake output on Windows?

**Comment by Huy-Ngo** [comment]
Oh, I thought I has included that already. [Here](https://gist.github.com/Huy-Ngo/f6ada1cbeab8a2bb9f574d883b26c13b) are the output btw

**Comment by McSinyx** [comment]
I mean the CMake output running in palace, showing which DLLs MSVC trynna link.

**Comment by Huy-Ngo** [comment]
I see, I'm gonna try tmr bc I'm having a headache rn

**Comment by McSinyx** [comment]
*[Discussion moved to the mailing list](https://lists.sr.ht/~cnx/palace/%3CC71E38RSHROZ.10K9QMGEBZQMI%40debian%3E).*
